# Attestify Kernel - Open Source

[package]
name = "kernel_oss"
version = "0.2.2"
edition = "2024"

[dependencies]
url = "2.5.4"

[dev-dependencies]
attestify_test_framework = { git = "https://github.com/attestify/test-framework-oss.git", tag = "v0.1.1" }